version: '3'
services:
  apache:
    image: php:7.4-apache
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /root/hosting/websites/apache-configs:/etc/apache2
      - /root/hosting/websites/files:/var/www
      - /root/hosting/websites/php-configs:/usr/local/etc/php
  database:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: DATABASE_PASS
    volumes:
      - /root/hosting/database/files:/var/lib/mysql
      - /root/hosting/database/configs:/etc/mysql/conf.d
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: database
    ports:
      - 8080:8080
  mailserver:
    image: h0perium/postfix-dovecot-dkim
    restart: always
    ports:
      - 25:25
      - 993:993
      - 995:995
      - 587:587
      - 143:143
      - 110:110
    volumes:
      - mailserver-storage:/var/mail
    environment:
      MTP_HOST: webiox.net
      INIT_EMAIL: info@webiox.net
      INIT_EMAIL_PASS: DATABASE_PASS
      MTP_DESTINATION: '6a6a6586e71d, localhost.localdomain, localhost'
  roundcube:
    depends_on:
      - database
    image: h0perium/roundcube
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: "mailserver"
      ROUNDCUBEMAIL_SMTP_SERVER:  "mailserver"
      ROUNDCUBEMAIL_SMTP_PORT: 25
      ROUNDCUBEMAIL_DB_TYPE: mysql
      ROUNDCUBEMAIL_DB_HOST: database
      ROUNDCUBEMAIL_DB_USER: root
      ROUNDCUBEMAIL_DB_PASSWORD: divaneh1452
      ROUNDCUBEMAIL_DB_NAME: admin

    ports:
      - 8880:80
    restart: always
volumes:
   mailserver-storage:
